[package]
name = "chocoSocks"
version = "0.1.0"
authors = ["Eva"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
cpython = { version = "0.2.0", features = ["python-3-7"] }