reorder_imports = true
indent_style = "Block"
control_brace_style = "AlwaysNextLine"
brace_style = "AlwaysNextLine"
where_single_line = "true"
hard_tabs = "true"
imports_layout = "Vertical"
merge_imports = "true"
merge_derives = "true"