[package]
name = "python_interop"
version = "0.1.0"
authors = ["bob <1ulsg@live.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpython = { version = "0.2.0", features = ["python-3-7"] }
